# Generated by Django 4.2.7 on 2024-01-12 06:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.UUIDField(default=uuid.uuid4)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, null=True, verbose_name="Correo Electrónico"
                    ),
                ),
                ("email_verified", models.BooleanField(default=False)),
                ("created", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="ShortUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=20)),
                ("url", models.URLField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shortener.user"
                    ),
                ),
            ],
        ),
    ]
