# Generated by Django 4.2.7 on 2024-01-13 04:42

from django.db import migrations, models
import shortener.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shorturl",
            name="key",
            field=models.CharField(
                default=shortener.models.ShortUrl.generate_key, max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="key",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
