# Generated by Django 4.2.7 on 2024-01-13 05:07

from django.db import migrations, models
import shortener.models


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0002_alter_shorturl_key_alter_user_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shorturl",
            name="key",
            field=models.CharField(
                default=shortener.models.ShortUrl.generate_key,
                max_length=20,
                unique=True,
            ),
        ),
    ]
