name: Docker Image CI

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      tagname: $(date +%s)
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t ${{ vars.DOCKER_REPO_NAME }}:${{ env.tagname }}
    - name: Publish the Docker image
      run: docker push ${{ vars.DOCKER_REPO_NAME }}:${{ env.tagname }}

