name: Docker Image CI

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      tagname: $(date +%s)
      repo: ${{ vars.DOCKER_USER }}/${{ vars.DOCKER_REPO_NAME }}
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USER }}
        password: ${{ secrets.DOCKER_SECRET }}
    - name: Build the Docker image
      run: docker build . -t ${{ env.repo }}:latest
    - run: docker tag ${{ env.repo }} ${{ env.repo }}:${{ env.tagname }}
    - name: Publish the Docker image
      run: docker push -a ${{ env.repo }}

