name: Docker Image CI

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      tagname: $(date +%s)
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_SECRET }}
    - name: Build the Docker image
      run: docker build . -t ${{ vars.DOCKER_REPO_NAME }}:${{ env.tagname }}
    - run: docker tag ${{ vars.DOCKER_REPO_NAME }} ${{ vars.DOCKER_REPO_NAME }}:latest
    - name: Publish the Docker image
      run: docker push -a ${{ vars.DOCKER_REPO_NAME }}

